# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: johnny/sources/interactive_csv/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+johnny/sources/interactive_csv/config.proto\x12\x12johnny.interactive\"\xa6\x01\n\x06\x43onfig\x12\x31\n)transactions_flex_report_csv_file_pattern\x18\x01 \x01(\t\x12.\n&positions_flex_report_csv_file_pattern\x18\x02 \x01(\t\x12\x39\n\x11\x66\x61llback_database\x18\x03 \x01(\x0b\x32\x1e.johnny.interactive.FallbackDB\"q\n\nFallbackDB\x12-\n\x05\x62\x65tas\x18\x01 \x03(\x0b\x32\x1e.johnny.interactive.DatedValue\x12\x34\n\x0cindex_prices\x18\x02 \x03(\x0b\x32\x1e.johnny.interactive.DatedValue\"9\n\nDatedValue\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02')



_CONFIG = DESCRIPTOR.message_types_by_name['Config']
_FALLBACKDB = DESCRIPTOR.message_types_by_name['FallbackDB']
_DATEDVALUE = DESCRIPTOR.message_types_by_name['DatedValue']
Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'johnny.sources.interactive_csv.config_pb2'
  # @@protoc_insertion_point(class_scope:johnny.interactive.Config)
  })
_sym_db.RegisterMessage(Config)

FallbackDB = _reflection.GeneratedProtocolMessageType('FallbackDB', (_message.Message,), {
  'DESCRIPTOR' : _FALLBACKDB,
  '__module__' : 'johnny.sources.interactive_csv.config_pb2'
  # @@protoc_insertion_point(class_scope:johnny.interactive.FallbackDB)
  })
_sym_db.RegisterMessage(FallbackDB)

DatedValue = _reflection.GeneratedProtocolMessageType('DatedValue', (_message.Message,), {
  'DESCRIPTOR' : _DATEDVALUE,
  '__module__' : 'johnny.sources.interactive_csv.config_pb2'
  # @@protoc_insertion_point(class_scope:johnny.interactive.DatedValue)
  })
_sym_db.RegisterMessage(DatedValue)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIG._serialized_start=68
  _CONFIG._serialized_end=234
  _FALLBACKDB._serialized_start=236
  _FALLBACKDB._serialized_end=349
  _DATEDVALUE._serialized_start=351
  _DATEDVALUE._serialized_end=408
# @@protoc_insertion_point(module_scope)
