# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: johnny/sources/tastytrade/config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&johnny/sources/tastytrade/config.proto\x12\x11johnny.tastytrade\"B\n\x06\x43onfig\x12\x14\n\x0c\x64\x62m_filename\x18\x01 \x01(\t\x12\"\n\x1apositions_csv_file_pattern\x18\x02 \x01(\t')



_CONFIG = DESCRIPTOR.message_types_by_name['Config']
Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'johnny.sources.tastytrade.config_pb2'
  # @@protoc_insertion_point(class_scope:johnny.tastytrade.Config)
  })
_sym_db.RegisterMessage(Config)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIG._serialized_start=61
  _CONFIG._serialized_end=127
# @@protoc_insertion_point(module_scope)
