# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: johnny/base/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18johnny/base/common.proto\x12\x06johnny\"\n\n\x08\x44\x61teTime\"\t\n\x07\x44\x65\x63imal')



_DATETIME = DESCRIPTOR.message_types_by_name['DateTime']
_DECIMAL = DESCRIPTOR.message_types_by_name['Decimal']
DateTime = _reflection.GeneratedProtocolMessageType('DateTime', (_message.Message,), {
  'DESCRIPTOR' : _DATETIME,
  '__module__' : 'johnny.base.common_pb2'
  # @@protoc_insertion_point(class_scope:johnny.DateTime)
  })
_sym_db.RegisterMessage(DateTime)

Decimal = _reflection.GeneratedProtocolMessageType('Decimal', (_message.Message,), {
  'DESCRIPTOR' : _DECIMAL,
  '__module__' : 'johnny.base.common_pb2'
  # @@protoc_insertion_point(class_scope:johnny.Decimal)
  })
_sym_db.RegisterMessage(Decimal)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATETIME._serialized_start=36
  _DATETIME._serialized_end=46
  _DECIMAL._serialized_start=48
  _DECIMAL._serialized_end=57
# @@protoc_insertion_point(module_scope)
