# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: johnny/base/nontrades.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bjohnny/base/nontrades.proto\x12\x06johnny\"\n\n\x08\x44\x61teTime\"\t\n\x07\x44\x65\x63imal\"\xa3\x02\n\x08NonTrade\x12)\n\x07rowtype\x18\x01 \x02(\x0e\x32\x18.johnny.NonTrade.RowType\x12\x0f\n\x07\x61\x63\x63ount\x18\x02 \x02(\t\x12\x16\n\x0etransaction_id\x18\x03 \x02(\t\x12\"\n\x08\x64\x61tetime\x18\x04 \x02(\x0b\x32\x10.johnny.DateTime\x12\x13\n\x0b\x64\x65scription\x18\x05 \x02(\t\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x0e\n\x06symbol\x18\x07 \x01(\t\x12\x0b\n\x03ref\x18\x08 \x01(\t\x12 \n\x06\x61mount\x18\t \x02(\x0b\x32\x10.johnny.DateTime\x12!\n\x07\x62\x61lance\x18\n \x01(\x0b\x32\x10.johnny.DateTime\"\x1a\n\x07RowType\x12\x0f\n\x0b\x43\x61shBalance\x10\x01')



_DATETIME = DESCRIPTOR.message_types_by_name['DateTime']
_DECIMAL = DESCRIPTOR.message_types_by_name['Decimal']
_NONTRADE = DESCRIPTOR.message_types_by_name['NonTrade']
_NONTRADE_ROWTYPE = _NONTRADE.enum_types_by_name['RowType']
DateTime = _reflection.GeneratedProtocolMessageType('DateTime', (_message.Message,), {
  'DESCRIPTOR' : _DATETIME,
  '__module__' : 'johnny.base.nontrades_pb2'
  # @@protoc_insertion_point(class_scope:johnny.DateTime)
  })
_sym_db.RegisterMessage(DateTime)

Decimal = _reflection.GeneratedProtocolMessageType('Decimal', (_message.Message,), {
  'DESCRIPTOR' : _DECIMAL,
  '__module__' : 'johnny.base.nontrades_pb2'
  # @@protoc_insertion_point(class_scope:johnny.Decimal)
  })
_sym_db.RegisterMessage(Decimal)

NonTrade = _reflection.GeneratedProtocolMessageType('NonTrade', (_message.Message,), {
  'DESCRIPTOR' : _NONTRADE,
  '__module__' : 'johnny.base.nontrades_pb2'
  # @@protoc_insertion_point(class_scope:johnny.NonTrade)
  })
_sym_db.RegisterMessage(NonTrade)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATETIME._serialized_start=39
  _DATETIME._serialized_end=49
  _DECIMAL._serialized_start=51
  _DECIMAL._serialized_end=60
  _NONTRADE._serialized_start=63
  _NONTRADE._serialized_end=354
  _NONTRADE_ROWTYPE._serialized_start=328
  _NONTRADE_ROWTYPE._serialized_end=354
# @@protoc_insertion_point(module_scope)
